version: "3"
services:
  web:
    build: ./
    volumes:
      - ./src/presence_analyzer:/code/src/presence_analyzer
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
